language: python
python:
  - "2.7"

install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/SROMPy
  - pip install scipy
  - pip install matplotlib
  - pip install pytest==4.0 pytest-cov
  - pip install coveralls

script:
  - pytest tests --cov=SROMPy

after_script:
  - coveralls
